import { Button } from "@/components/shared/Button";

interface SignalsSourcesSectionProps {
  settings: Record<string, unknown>;
  onSave: (key: string, value: number) => void;
  /** "local" | "remote" | "centralized" — where an engine control lands. */
  controlTarget?: string;
}

interface Source {
  key: string;
  title: string;
  blurb: string;
  onLabel: string;
  offLabel: string;
  /** What an install that has never touched this does. */
  defaultOn: boolean;
  help: string;
}

/**
 * The per-source live-execution gates, restored 2026-09-18.
 *
 * **These decide whether signals become real MT5 trades.** They lived at the
 * top of the Parsing page from 2026-07-22 and the React port dropped them, so
 * between then and now there was no way to stop an engine executing except by
 * editing the database — the wrong thing to be doing at the moment you want an
 * engine to stop.
 *
 * Wording transcribed from `frontend/pages/trading/_signals_card.py` rather
 * than rewritten: each of these sentences is the difference between "learning
 * mode" and "this opens positions", and a paraphrase is how somebody turns the
 * wrong one on.
 *
 * They write this node's own settings row. The AI-evaluation switches beside
 * them route to whichever node is trading (`/api/engines/ai-eval`), because the
 * sync protocol carries those and carries nothing else — so in Remote mode
 * these three change what THIS machine would do, which is not the machine
 * placing the trades. The banner says so rather than leaving it to be guessed.
 */
const SOURCES: Source[] = [
  {
    key: "accept_tg_signals",
    title: "Telegram Signals",
    blurb: "Accept and trade signals from Telegram channels",
    onLabel: "TG SIGNALS ON",
    offLabel: "TG SIGNALS OFF",
    defaultOn: true,
    help:
      "When ON, Telegram signals from your configured channels are parsed and " +
      "can be auto-executed. When OFF, incoming Telegram messages are collected " +
      "but completely ignored — no signals are created or traded.",
  },
  {
    key: "bo_live_execution",
    title: "Breakout",
    blurb: "Route breakout signals to MT5 as live trades",
    onLabel: "BO LIVE ON",
    offLabel: "BO LIVE OFF",
    defaultOn: false,
    help:
      "When ON, confirmed breakout signals are sent to MT5 as live trades. When " +
      "OFF, the engine runs in virtual/learning-only mode. Use the Signal " +
      "Generator tab to start/stop the engine and view signals.",
  },
  {
    key: "re_live_execution",
    title: "Reversal Engine",
    blurb: "Route Reversal Engine signals to MT5 as live trades",
    onLabel: "RE LIVE ON",
    offLabel: "RE LIVE OFF",
    defaultOn: false,
    help:
      "When ON, signals generated by the Reversal Engine are executed as real " +
      "MT5 trades. The engine reverse-engineers the channel's methodology to " +
      "generate signals before they arrive on Telegram. Use Signal Generator > " +
      "Reversal Engine to view signals and correlation stats.",
  },
];

function isOn(settings: Record<string, unknown>, s: Source): boolean {
  const raw = settings[s.key];
  return raw === undefined || raw === null ? s.defaultOn : Boolean(Number(raw));
}

export function SignalsSourcesSection(
  { settings, onSave, controlTarget = "local" }: SignalsSourcesSectionProps,
) {
  return (
    <section data-testid="signal-sources" className="rounded border border-line p-3">
      <h3 className="text-xs font-semibold text-ink-1">Signals</h3>
      <p className="mb-3 text-[11px] text-ink-3">
        Which sources may open real positions. Off means the source still runs
        and still records what it would have done — it just does not trade.
      </p>

      {controlTarget === "remote" && (
        <p className="mb-3 rounded border border-remote/40 bg-remote/10 px-2 py-1.5 text-[11px] text-remote">
          The remote node is the active trader. These three set what{" "}
          <strong>this machine</strong> would do; they do not travel between
          nodes, so set them on whichever machine is trading.
        </p>
      )}

      <div className="grid gap-3 sm:grid-cols-3">
        {SOURCES.map((s) => {
          const on = isOn(settings, s);
          return (
            <div
              key={s.key}
              data-testid={`source-${s.key}`}
              className="flex flex-col rounded border border-line bg-surface-2 p-2.5"
            >
              <span className="text-xs font-semibold text-ink-1" title={s.help}>
                {s.title}
              </span>
              <span className="mt-0.5 text-[11px] leading-snug text-ink-3">
                {s.blurb}
              </span>
              <div className="mt-2">
                <Button
                  variant="ghost"
                  aria-pressed={on}
                  onClick={() => onSave(s.key, on ? 0 : 1)}
                  title={s.help}
                >
                  <span className={on ? "text-profit" : "text-ink-3"}>
                    {on ? s.onLabel : s.offLabel}
                  </span>
                </Button>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
